# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: vcpkg Windows

on:
  push:
    branches:
      - master
      - '*/ci'
    paths-ignore:
      - '**/*.md'
      - '.azure-pipelines.yml'
      - '.circleci/**'
      - '.cirrus.yml'
      - 'appveyor.*'
      - 'packages/**'
      - 'plan9/**'
      - 'projects/**'
      - 'winbuild/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.azure-pipelines.yml'
      - '.circleci/**'
      - '.cirrus.yml'
      - 'appveyor.*'
      - 'packages/**'
      - 'plan9/**'
      - 'projects/**'
      - 'winbuild/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  OS: windows
  BUILD_DIR: vcpkg/cache
  VCPKG_LINK: https://github.com/microsoft/vcpkg/
  BINARY_CACHE: vcpkg/cache/linux
  VCPKG_ROOT_WINDOWS: vcpkg/cache/vcpkg

jobs:
  build:
    name: vcpkg-windows-${{ matrix.PROCESSOR }}-${{ matrix.BUILD_OPTION }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - BUILD_OPTION: openssl
          PROCESSOR: x64
          CMAKE_OPTIONS: -DCURL_USE_LIBSSH2=ON 
        - BUILD_OPTION: libressl
          PROCESSOR: x64
          CMAKE_OPTIONS: -DCURL_USE_LIBSSH2=OFF
    env:
      PROCESSOR: ${{ matrix.PROCESSOR }}
      BUILD_OPTION: ${{ matrix.BUILD_OPTION }}
      CMAKE_OPTIONS: ${{ matrix.CMAKE_OPTIONS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{env.BINARY_CACHE }}/${{ matrix.BUILD_OPTION }}
          key: ${{ env.OS }}-${{ matrix.BUILD_OPTION }}-${{ hashFiles('.github/workflows/vcpkg-windows.yml') }}
          restore-keys: ${{ env.OS }}-${{ matrix.BUILD_OPTION }}-${{ hashFiles('.github/workflows/vcpkg-windows.yml') }}

      - name: Setup msbuild
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.PROCESSOR }}    

      - name: cl version
        shell: cmd
        run: |
          cl

      - name: Fix vcpkg
        shell: cmd
        run: vcpkg.exe integrate remove

      - name: Init vcpkg
        if: success()
        shell: bash
        run: |
          mkdir -p $BUILD_DIR
          git -C $BUILD_DIR clone $VCPKG_LINK
          $VCPKG_ROOT_WINDOWS/bootstrap-vcpkg.sh
  
      - name: vcpkg build openssl
        shell: bash
        if: ${{ success() && matrix.BUILD_OPTION == 'openssl' }}
        run: |
          export VCPKG_ROOT=$VCPKG_ROOT_WINDOWS
          export CURRENT_BINARY_CACHE="$BINARY_CACHE/$BUILD_OPTION"
          mkdir -p $CURRENT_BINARY_CACHE
          export VCPKG_BINARY_SOURCES="clear;files,${GITHUB_WORKSPACE}/$CURRENT_BINARY_CACHE,readwrite;"
          $VCPKG_ROOT_WINDOWS/vcpkg x-set-installed libssh2[core,openssl] nghttp2 openssl zstd --triplet=$PROCESSOR-$OS-release

      - name: vcpkg build libressl
        shell: bash
        if: ${{ success() && matrix.BUILD_OPTION == 'libressl' }}
        run: |
          export VCPKG_ROOT=$VCPKG_ROOT_WINDOWS
          export CURRENT_BINARY_CACHE="$BINARY_CACHE/$BUILD_OPTION"
          mkdir -p $CURRENT_BINARY_CACHE
          export VCPKG_BINARY_SOURCES="clear;files,${GITHUB_WORKSPACE}/$CURRENT_BINARY_CACHE,readwrite;"
          $VCPKG_ROOT_WINDOWS/vcpkg x-set-installed libressl nghttp2 zstd --triplet=$PROCESSOR-$OS-release

      - name: cmake config
        if: success() 
        shell: bash
        run: |
          export VCPKG_ROOT=$VCPKG_ROOT_WINDOWS
          export CMAKE_GENERATOR=Ninja
          cmake . -B build \
              -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT_WINDOWS/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_INSTALLED_DIR=$VCPKG_ROOT_WINDOWS/installed \
              -DVCPKG_TARGET_TRIPLET=$PROCESSOR-$OS-release \
              -DCMAKE_UNITY_BUILD=ON \
              -DCURL_WERROR=ON \
              -DBUILD_SHARED_LIBS=OFF \
              -DCURL_ZSTD=ON \
              -DUSE_NGHTTP2=ON \
              -DCURL_USE_LIBPSL=OFF \
              -DCURL_USE_GSSAPI=OFF \
              -DENABLE_ARES=OFF \
              -DCURL_USE_LIBSSH=OFF \
              $CMAKE_OPTIONS

      - name: Prepare logs on failure
        if: failure()
        shell: bash
        run: |
          7z a -t7z -r -mx=9 logs.7z \
              $VCPKG_ROOT_WINDOWS/buildtrees/*.log \
              build/.ninja_log \
              build/build.ninja \
              build/install_manifest.txt \
              build/vcpkg-manifest-install.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: windows_logs_${{matrix.BUILD_OPTION}}_${{github.event.pull_request.head.sha}}
          path: logs.7z

      - name: Save cache dependencies
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{env.BINARY_CACHE }}/${{ matrix.BUILD_OPTION }}
          key: ${{ env.OS }}-${{ matrix.BUILD_OPTION }}-${{ hashFiles('.github/workflows/vcpkg-windows.yml') }}-${{ hashFiles('vcpkg/cache/vcpkg/installed/vcpkg/updates/*') }}

      - name: Cmake build
        if: success()
        shell: bash
        run: |
          cmake --build build --config Release -j2
          export PATH=$PWD/$VCPKG_ROOT_WINDOWS/installed/x64-windows-release/bin:$PATH
          build/src/curl --disable --version

      - name: Cmake install
        if: success()
        shell: bash
        run: |
          cmake --install build --config Release

      - name: Run tests
        if: success() 
        shell: bash
        run: |
          export PATH=$PWD/$VCPKG_ROOT_WINDOWS/installed/x64-windows-release/bin:$PATH
          cmake --build build --target test-ci -j2
