# Copyright (C) Viktor Szakats
#
# SPDX-License-Identifier: curl

name: Windows

'on':
  push:
    branches:
      - master
      - '*/ci'
    paths-ignore:
      - '**/*.md'
      - '.circleci/**'
      - 'appveyor.*'
      - 'packages/**'
      - 'plan9/**'
      - 'projects/**'
      - 'winbuild/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.circleci/**'
      - 'appveyor.*'
      - 'packages/**'
      - 'plan9/**'
      - 'projects/**'
      - 'winbuild/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  wince:
    name: "cygwin-mingw32ce, ${{ matrix.build == 'cmake' && 'CM' || 'AM' }} 4.4.0-arm schannel"
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe '{0}'
    env:
      toolchain-version: '0.59.1'
      SHELLOPTS: 'igncr'
    strategy:
      matrix:
        build: [autotools, cmake]
      fail-fast: false
    steps:
      - run: git config --global core.autocrlf input
        shell: pwsh

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 'cache compiler (mingw32ce)'
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        id: cache-compiler
        with:
          path: opt/mingw32ce
          key: ${{ runner.os }}-mingw32ce-${{ env.toolchain-version }}-amd32

      - name: 'install compiler (mingw32ce)'
        if: ${{ steps.cache-compiler.outputs.cache-hit != 'true' }}
        shell: cmd
        run: |
          curl -L https://downloads.sourceforge.net/cegcc/cegcc/${{ env.toolchain-version }}/cegcc_mingw32ce_cygwin1.7_r1399.tar.bz2 -o cegcc_mingw32ce_cygwin1.7_r1399.tar.bz2
          7z x cegcc_mingw32ce_cygwin1.7_r1399.tar.bz2
          7z x cegcc_mingw32ce_cygwin1.7_r1399.tar

      - uses: cygwin/cygwin-install-action@f61179d72284ceddc397ed07ddb444d82bf9e559 # v5
        with:
          platform: x86
          site: http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/2015/02/10/141012/
          check-sig: false
          packages: >-
            autoconf libtool binutils
            automake make
            curl unzip
            libmpfr1

      - name: 'vcpkg'
        run: | 
          MINGW32CE_ROOT="$(cygpath -m $(pwd))/opt/mingw32ce"
          PATH="/usr/bin:$(pwd)/opt/mingw32ce/bin:$(pwd)"
          arm-mingw32ce-gcc.exe --version

          export CC="arm-mingw32ce-gcc.exe"
          export CXX="arm-mingw32ce-g++.exe"
          export AR="arm-mingw32ce-ar.exe"
          export RANLIB="arm-mingw32ce-ranlib.exe"
          export RC="arm-mingw32ce-windres.exe"
          export CMAKE_GENERATOR_TOOLSET="CE800"
          echo CC: $CC
          cat <<EOF > C:/vcpkg/triplets/community/arm-mingw32ce-static.cmake
          set(VCPKG_TARGET_ARCHITECTURE arm)
          set(VCPKG_CRT_LINKAGE dynamic)
          set(VCPKG_LIBRARY_LINKAGE dynamic)
          set(VCPKG_ENV_PASSTHROUGH PATH)

          set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
          set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)

          set(VCPKG_CMAKE_HOST_SYSTEM_NAME cygwin)
          set(VCPKG_CMAKE_SYSTEM_VERSION 8)
          set(VCPKG_CMAKE_GENERATOR_TOOLSET CE800)
          EOF
          curl -L https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip -o ninja-win.zip
          unzip ninja-win.zip
          ninja.exe --version
          c:/vcpkg/vcpkg install zlib --triplet=arm-mingw32ce-static
          cat 

      - name: 'configure'
        run: | 
          cat <<EOF > vcpkg.json
          {
              "name": "curl",
              "dependencies":
              [
                "zlib"
              ]
          }
          EOF

          MINGW32CE_ROOT="$(cygpath -m $(pwd))/opt/mingw32ce"
          PATH="/usr/bin:$(pwd)/opt/mingw32ce/bin:$(pwd)"
          curl -L https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip -o ninja-win.zip
          unzip ninja-win.zip
          ninja.exe --version
          if [ '${{ matrix.build }}' = 'cmake' ]; then

              # -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" \
              # -DVCPKG_INSTALLED_DIR="C:/vcpkg/installed" \
              # -DVCPKG_TARGET_TRIPLET=arm-mingw-static \

            "/cygdrive/c/Program Files/CMake/bin/cmake.exe" -B bld -G "Ninja" \
              -DCMAKE_SYSTEM_NAME=WindowsCE \
              -DCMAKE_SYSTEM_VERSION=8.0 \
              -DCMAKE_SYSTEM_PROCESSOR=arm \
              -DCMAKE_C_COMPILER_TARGET=arm-wince-mingw32ce \
              -DCMAKE_C_COMPILER="arm-mingw32ce-gcc.exe" \
              -DCMAKE_RC_COMPILER="arm-mingw32ce-windres.exe" \
              -DMINGW32CE_LIBRARY_DIR="${MINGW32CE_ROOT}/arm-mingw32ce/lib" \
              -DCMAKE_UNITY_BUILD=ON -DCURL_TEST_BUNDLES=ON \
              -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DBUILD_STATIC_CURL=OFF \
              -DCURL_WERROR=ON \
              -DCURL_USE_SCHANNEL=ON \
              -DCURL_USE_LIBPSL=OFF

              # echo =======================================================
              # cat C:/vcpkg/buildtrees/detect_compiler/config-arm-mingw-static-out.log
          else
            autoreconf -fi
            mkdir bld && cd bld && ../configure --disable-dependency-tracking --enable-unity --enable-test-bundles --enable-warnings --enable-werror \
              ac_cv_prog_cc_c99=no \
              CC="${MINGW32CE_ROOT}/bin/arm-mingw32ce-gcc.exe" \
              AR="${MINGW32CE_ROOT}/bin/arm-mingw32ce-ar.exe" \
              RANLIB="${MINGW32CE_ROOT}/bin/arm-mingw32ce-ranlib.exe" \
              RC="${MINGW32CE_ROOT}/bin/arm-mingw32ce-windres.exe" \
              --host=arm-wince-mingw32ce \
              --with-schannel \
              --without-libpsl \
              --disable-shared
          fi

      - name: 'configure log'
        if: ${{ !cancelled() }}
        run: cat bld/config.log bld/CMakeFiles/CMake*.yaml 2>/dev/null || true

      - name: 'curl_config.h'
        run: |
          echo '::group::raw'; cat bld/lib/curl_config.h || true; echo '::endgroup::'
          grep -F '#define' bld/lib/curl_config.h | sort || true

      - name: 'build'
        run: |
          if [ '${{ matrix.build }}' = 'cmake' ]; then
            MINGW32CE_ROOT="$(pwd)/opt/mingw32ce"
            PATH="/usr/bin:${MINGW32CE_ROOT}/bin"
            "C:/Program Files/CMake/bin/cmake.exe" --build bld
          else
            make -j5 -C bld
          fi

      - name: 'curl info'
        run: |
          find . \( -name '*.exe' -o -name '*.dll' -o -name '*.a' \) -exec file '{}' \;

      - name: 'build tests'
        run: |
          if [ '${{ matrix.build }}' = 'cmake' ]; then
            MINGW32CE_ROOT="$(pwd)/opt/mingw32ce"
            PATH="/usr/bin:${MINGW32CE_ROOT}/bin"
            "C:/Program Files/CMake/bin/cmake.exe" --build bld --target testdeps
          else
            make -j5 -C bld -C tests
          fi

      - name: 'build examples'
        run: |
          if [ '${{ matrix.build }}' = 'cmake' ]; then
            MINGW32CE_ROOT="$(pwd)/opt/mingw32ce"
            PATH="/usr/bin:${MINGW32CE_ROOT}/bin"
            "C:/Program Files/CMake/bin/cmake.exe" --build bld --target curl-examples
          else
            make -j5 -C bld examples
          fi
